PAGE_CONFIGS = {
    "Members": {
        "table": "members",
        "pk": "member_id",
        "display_columns": [
            "member_id",
            "member_name",
            "contact_number",
            "membership_type",
            "membership_status",
            "membership_expiry",
        ],
        "headings": [
            "Member ID",
            "Name",
            "Contact",
            "Type",
            "Status",
            "Expiry",
        ],
        "search_columns": [
            "member_id",
            "member_name",
            "contact_number",
            "membership_type",
            "membership_status",
        ],
        "fields": [
            ("Member Name", "member_name", "text"),
            ("Residence Address", "residence_address", "text"),
            ("Contact Number", "contact_number", "contact"),
            ("Membership Type", "membership_type", "dropdown"),
            ("Medical Clearance", "medical_clearance", "dropdown"),
            ("Health Issues", "health_issues", "multiline"),
            ("Membership Registered", "membership_registered", "readonly"),
            ("Membership Duration", "membership_duration", "dropdown"),
            ("Membership Expiry", "membership_expiry", "readonly"),
            ("Membership Status", "membership_status", "readonly"),
            ("Days Remaining", "days_remaining", "readonly"),
        ],
    },
    "Trainers": {
        "table": "trainers",
        "pk": "trainer_id",
        "required_fields": [
            "trainer_name",
            "email",
            "contact_number",
            "specialization",
        ],
        "admin_only_fields": [
            "salary",
            "hire_date",
            "years_experience",
        ],
        "display_columns": [
            "trainer_id",
            "trainer_name",
            "email",
            "contact_number",
            "specialization",
            "years_experience",
        ],
        "headings": [
            "Trainer ID",
            "Name",
            "Email",
            "Contact",
            "Specialization",
            "Experience",
        ],
        "search_columns": [
            "trainer_id",
            "trainer_name",
            "email",
            "contact_number",
            "specialization",
        ],
        "fields": [
            ("User Account ID", "user_id", "readonly"),
            ("Trainer Name", "trainer_name", "account"),
            ("Email", "email", "account_email"),
            ("Contact Number", "contact_number", "account_contact"),
            ("Specialization", "specialization", "dropdown"),
            ("Salary", "salary", "float"),
            ("Hire Date", "hire_date", "date"),
            ("Years Experience", "years_experience", "int"),
        ],
    },
    "Class Sessions": {
        "table": "class_sessions",
        "pk": "session_id",
        "display_columns": [
            "session_id",
            "class_name",
            "schedule",
            "capacity",
            "assigned_trainer",
        ],
        "headings": [
            "Session ID",
            "Class Name",
            "Schedule",
            "Capacity",
            "Trainer",
        ],
        "search_columns": [
            "session_id",
            "class_name",
            "schedule",
            "assigned_trainer",
        ],
        "fields": [
            ("Class Name", "class_name", "text"),
            ("Schedule", "schedule", "text"),
            ("Capacity", "capacity", "int"),
            ("Assigned Trainer", "assigned_trainer", "dropdown"),
        ],
    },
    "Class Enrollment": {
        "table": "class_enrollment",
        "pk": "enrollment_id",
        "display_columns": [
            "enrollment_id",
            "member_id",
            "session_id",
            "enrolled_date",
        ],
        "headings": [
            "Enrollment ID",
            "Member ID",
            "Session ID",
            "Enrolled Date",
        ],
        "search_columns": [
            "enrollment_id",
            "member_id",
            "session_id",
            "enrolled_date",
        ],
        "fields": [
            ("Member ID", "member_id", "lookup"),
            ("Session ID", "session_id", "lookup"),
            ("Enrolled Date", "enrolled_date", "date"),
        ],
    },
    "Attendance": {
        "table": "attendance",
        "pk": "attendance_id",
        "display_columns": [
            "attendance_id",
            "member_id",
            "session_id",
            "check_in_time",
        ],
        "headings": [
            "Attendance ID",
            "Member ID",
            "Session ID",
            "Check-In Time",
        ],
        "search_columns": [
            "attendance_id",
            "member_id",
            "session_id",
            "check_in_time",
        ],
        "fields": [
            ("Member ID", "member_id", "lookup"),
            ("Session ID", "session_id", "lookup"),
            ("Check-In Time", "check_in_time", "text"),
        ],
    },
    "Equipment": {
        "table": "equipment",
        "pk": "equipment_id",
        "display_columns": [
            "equipment_id",
            "equipment_name",
            "category",
            "status",
            "purchase_cost",
            "age_of_equipment",
        ],
        "headings": [
            "Equipment ID",
            "Name",
            "Category",
            "Status",
            "Cost",
            "Age",
        ],
        "search_columns": [
            "equipment_id",
            "equipment_name",
            "category",
            "status",
        ],
        "fields": [
            ("Equipment Name", "equipment_name", "text"),
            ("Category", "category", "dropdown"),
            ("Status", "status", "dropdown"),
            ("Purchase Date", "purchase_date", "date"),
            ("Purchase Cost", "purchase_cost", "float"),
            ("Age of Equipment", "age_of_equipment", "text"),
        ],
    },
    "Equipment Logs": {
        "table": "equipment_logs",
        "pk": "log_id",
        "display_columns": [
            "log_id",
            "equipment_id",
            "action_taken",
            "log_date",
        ],
        "headings": [
            "Log ID",
            "Equipment ID",
            "Action Taken",
            "Log Date",
        ],
        "search_columns": [
            "log_id",
            "equipment_id",
            "action_taken",
            "log_date",
        ],
        "fields": [
            ("Equipment ID", "equipment_id", "lookup"),
            ("Action Taken", "action_taken", "text"),
            ("Log Date", "log_date", "date"),
        ],
    },
    "Transactions": {
        "table": "transactions",
        "pk": "transaction_id",
        "display_columns": [
            "transaction_id",
            "member_id",
            "amount",
            "transaction_date",
            "payment_type",
            "total_amount",
        ],
        "headings": [
            "Transaction ID",
            "Member ID",
            "Amount",
            "Date",
            "Payment Type",
            "Total",
        ],
        "search_columns": [
            "transaction_id",
            "member_id",
            "transaction_date",
            "payment_type",
        ],
        "fields": [
            ("Member ID", "member_id", "lookup"),
            ("Amount", "amount", "float"),
            ("Transaction Date", "transaction_date", "date"),
            ("Payment Type", "payment_type", "dropdown"),
            ("Total Amount", "total_amount", "float"),
        ],
    },
}


def get_page_config(page_name):
    return PAGE_CONFIGS[page_name]
